### ISSUE TITLE
Problem Upgrading to Angular 2.0.0-beta.1

### ISSUE THREAD

**Issue by marcojakob** [jwashin/angular2-rbi-dart#1]
I've upgraded to Angular 2.0.0-beta.1. Now I get the following error from angular2-rbi:

```
EXCEPTION: EXCEPTION: Error during instantiation of MaterialLayout!.
ORIGINAL EXCEPTION: The null object does not have a method 'insertBefore'.

NoSuchMethodError: method not found: 'insertBefore'
Receiver: null
Arguments: [Instance of 'DivElement', Instance of 'DivElement']
ORIGINAL STACKTRACE:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      LayoutBehavior.LayoutBehavior (package:angular2_rbi/src/directives/material_layout.dart:72:17)
#3      MaterialLayout.MaterialLayout (package:angular2_rbi/directives.dart:48:36)
#4      initReflector.<anonymous closure> (package:angular2_rbi/directives.ng_deps.dart:60:25)
#5      Injector._instantiate (package:angular2/src/core/di/injector.dart:894:24)
#6      Injector._instantiateProvider (package:angular2/src/core/di/injector.dart:791:12)
#7      Injector._new (package:angular2/src/core/di/injector.dart:777:17)
#8      InjectorInlineStrategy.instantiateProvider (package:angular2/src/core/di/injector.dart:240:26)
#9      ElementDirectiveInlineStrategy.init (package:angular2/src/core/linker/element.dart:713:11)
#10     AppElement.AppElement (package:angular2/src/core/linker/element.dart:368:22)
```

It's this line in `LayoutBehavior` that is causing the problem because `parent` is null:
`elem.parent.insertBefore(container, elem);`

I've looked at the [Angular CHANGELOG](https://github.com/angular/angular/blob/master/CHANGELOG.md) and found this breaking change that could be related to this:

> Component view is not yet created when component constructor is called. -> use onInit lifecycle callback to access the view of a component

**Comment by jwashin** [comment]
I'm not seeing this, but it seems a reasonable best practice to move DOM-accessing constructor code into an init() method and invoke that in ngOnInit(). I'll go ahead and do that for version 0.0.3 (now available). Let me know that this works for you, and I'll close this issue.

**Comment by marcojakob** [comment]
Thank you for the fast fix. That solved the problem for me.

Now I have other errors that I will have to track down. I have multiple TextFields that are in a loop of constantly being created and deleted. I'm not sure if they are from Angular2 or from RBI or a combination of both. Will let you know if it's something related to RBI.
